"""
exporters/docx_exporter.py
-----------------------------
Produces an editable .docx version of the RCA report, so engineers can
tweak wording before sharing it with stakeholders or attaching to a
ticket, instead of being locked into the read-only PDF.
"""

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    return h


def export_rca_docx(report: dict, output_path: str):
    incident = report.get("incident", {})
    rca = report.get("rca", {})
    clusters = report.get("clusters", [])
    anomalies = report.get("anomalies", [])

    doc = Document()

    title = doc.add_heading("Root Cause Analysis Report", level=0)
    sub = doc.add_paragraph("Generated by RCAi - Root Cause Analysis Intelligence")
    sub.runs[0].italic = True

    doc.add_paragraph(f"Incident ID: {incident.get('incident_id','-')}")
    doc.add_paragraph(f"Title: {incident.get('title','-')}")
    doc.add_paragraph(f"Reported By: {incident.get('reported_by','-')}")
    doc.add_paragraph(f"Window: {incident.get('start_time','-')} to {incident.get('end_time','-')}")

    _add_heading(doc, "Executive Summary", 1)
    doc.add_paragraph(rca.get("executive_summary", ""))

    rc = rca.get("root_cause", {})
    _add_heading(doc, "Root Cause (AI Inference)", 1)
    doc.add_paragraph(f"Statement: {rc.get('statement','')}")
    doc.add_paragraph(f"Confidence: {rc.get('confidence','')}")
    doc.add_paragraph(f"Reasoning: {rc.get('reasoning','')}")

    _add_heading(doc, "Confirmed Evidence", 1)
    evidence = rca.get("confirmed_evidence", [])
    if evidence:
        table = doc.add_table(rows=1, cols=2)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Finding"
        hdr[1].text = "Source Reference"
        for ev in evidence:
            row = table.add_row().cells
            row[0].text = str(ev.get("finding", ""))
            row[1].text = str(ev.get("source_reference", ""))
    else:
        doc.add_paragraph("No directly confirmed evidence items were returned.")

    _add_heading(doc, "Contributing Factors", 1)
    for cf in rca.get("contributing_factors", []):
        tag = "[CONFIRMED]" if "confirmed" in str(cf.get("type", "")).lower() else "[AI INFERENCE]"
        doc.add_paragraph(f"{tag} {cf.get('factor','')} - {cf.get('detail','')}", style="List Bullet")

    impact = rca.get("incident_impact", {})
    _add_heading(doc, "Incident Impact", 1)
    doc.add_paragraph(impact.get("summary", ""))
    doc.add_paragraph(f"Affected systems: {', '.join(impact.get('affected_systems', []))}")
    doc.add_paragraph(f"Estimated duration: {impact.get('estimated_duration','')}")
    doc.add_paragraph(f"User impact: {impact.get('user_impact','')}")

    _add_heading(doc, "Resolution Actions", 1)
    for a in rca.get("resolution_actions", []):
        doc.add_paragraph(f"[{a.get('priority','')}] {a.get('action','')}", style="List Bullet")

    _add_heading(doc, "Preventive Actions", 1)
    for a in rca.get("preventive_actions", []):
        doc.add_paragraph(f"({a.get('category','')}) {a.get('action','')}", style="List Bullet")

    _add_heading(doc, "Timeline Narrative", 1)
    doc.add_paragraph(rca.get("timeline_narrative", ""))

    _add_heading(doc, "Appendix A: Correlated Event Clusters", 1)
    table = doc.add_table(rows=1, cols=5)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    for i, h in enumerate(["Cluster", "Start", "End", "Sources", "Max Severity"]):
        hdr[i].text = h
    for c in clusters:
        row = table.add_row().cells
        row[0].text = str(c["cluster_id"])
        row[1].text = c["start_time"]
        row[2].text = c["end_time"]
        row[3].text = ", ".join(c["sources"])
        row[4].text = c["max_severity"]

    _add_heading(doc, "Appendix B: Detected Anomalies", 1)
    for a in anomalies:
        doc.add_paragraph(f"[{a.get('type')}] {a.get('explanation','')}", style="List Bullet")

    doc.save(output_path)
    return output_path
