"""
exporters/pdf_exporter.py
----------------------------
Renders a completed RCA report (incident + clusters + anomalies + rca)
into a polished PDF using reportlab. This is the "final conclusion PDF"
the engineer downloads and can attach to a ticket.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_LEFT
import html


def _esc(text):
    if text is None:
        return ""
    return html.escape(str(text))


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="RCATitle", fontSize=22, leading=26, spaceAfter=6,
                               textColor=colors.HexColor("#1a1f36"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="RCASubtitle", fontSize=11, textColor=colors.HexColor("#6b7280"),
                               spaceAfter=16))
    styles.add(ParagraphStyle(name="SectionHeading", fontSize=14, spaceBefore=16, spaceAfter=8,
                               textColor=colors.HexColor("#1a1f36"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="Body", fontSize=10, leading=15, alignment=TA_LEFT))
    styles.add(ParagraphStyle(name="EvidenceTag", fontSize=8, textColor=colors.white,
                               backColor=colors.HexColor("#2563eb"), fontName="Helvetica-Bold"))
    return styles


def export_rca_pdf(report: dict, output_path: str):
    incident = report.get("incident", {})
    rca = report.get("rca", {})
    clusters = report.get("clusters", [])
    anomalies = report.get("anomalies", [])

    styles = _styles()
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=2 * cm, bottomMargin=2 * cm,
                             leftMargin=2 * cm, rightMargin=2 * cm)
    story = []

    # ---- Header ----
    story.append(Paragraph("Root Cause Analysis Report", styles["RCATitle"]))
    story.append(Paragraph("Generated by RCAi - Root Cause Analysis Intelligence", styles["RCASubtitle"]))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e7eb"), thickness=1))
    story.append(Spacer(1, 10))

    meta_table = Table([
        ["Incident ID", _esc(incident.get("incident_id", "-"))],
        ["Title", _esc(incident.get("title", "-"))],
        ["Reported By", _esc(incident.get("reported_by", "-"))],
        ["Window", f"{_esc(incident.get('start_time','-'))}  to  {_esc(incident.get('end_time','-'))}"],
    ], colWidths=[4 * cm, 12 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6b7280")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # ---- Executive Summary ----
    story.append(Paragraph("Executive Summary", styles["SectionHeading"]))
    story.append(Paragraph(_esc(rca.get("executive_summary", "")), styles["Body"]))

    # ---- Root Cause ----
    rc = rca.get("root_cause", {})
    story.append(Paragraph("Root Cause (AI Inference)", styles["SectionHeading"]))
    story.append(Paragraph(f"<b>Statement:</b> {_esc(rc.get('statement',''))}", styles["Body"]))
    story.append(Paragraph(f"<b>Confidence:</b> {_esc(rc.get('confidence',''))}", styles["Body"]))
    story.append(Paragraph(f"<b>Reasoning:</b> {_esc(rc.get('reasoning',''))}", styles["Body"]))

    # ---- Confirmed Evidence ----
    story.append(Paragraph("Confirmed Evidence", styles["SectionHeading"]))
    evidence = rca.get("confirmed_evidence", [])
    if evidence:
        rows = [["#", "Finding", "Source Reference"]]
        for i, ev in enumerate(evidence, start=1):
            rows.append([str(i), Paragraph(_esc(ev.get("finding", "")), styles["Body"]),
                         Paragraph(_esc(ev.get("source_reference", "")), styles["Body"])])
        t = Table(rows, colWidths=[1 * cm, 10 * cm, 5 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No directly confirmed evidence items were returned.", styles["Body"]))

    # ---- Contributing factors ----
    story.append(Paragraph("Contributing Factors", styles["SectionHeading"]))
    for cf in rca.get("contributing_factors", []):
        tag = "[CONFIRMED]" if "confirmed" in str(cf.get("type", "")).lower() else "[AI INFERENCE]"
        story.append(Paragraph(f"<b>{tag}</b> {_esc(cf.get('factor',''))} - {_esc(cf.get('detail',''))}",
                                styles["Body"]))

    # ---- Impact ----
    impact = rca.get("incident_impact", {})
    story.append(Paragraph("Incident Impact", styles["SectionHeading"]))
    story.append(Paragraph(_esc(impact.get("summary", "")), styles["Body"]))
    story.append(Paragraph(f"<b>Affected systems:</b> {_esc(', '.join(impact.get('affected_systems', [])))}",
                            styles["Body"]))
    story.append(Paragraph(f"<b>Estimated duration:</b> {_esc(impact.get('estimated_duration',''))}",
                            styles["Body"]))
    story.append(Paragraph(f"<b>User impact:</b> {_esc(impact.get('user_impact',''))}", styles["Body"]))

    # ---- Resolution & Preventive actions ----
    story.append(Paragraph("Resolution Actions", styles["SectionHeading"]))
    for a in rca.get("resolution_actions", []):
        story.append(Paragraph(f"- [{_esc(a.get('priority',''))}] {_esc(a.get('action',''))}", styles["Body"]))

    story.append(Paragraph("Preventive Actions", styles["SectionHeading"]))
    for a in rca.get("preventive_actions", []):
        story.append(Paragraph(f"- ({_esc(a.get('category',''))}) {_esc(a.get('action',''))}", styles["Body"]))

    # ---- Timeline narrative ----
    story.append(Paragraph("Timeline Narrative", styles["SectionHeading"]))
    story.append(Paragraph(_esc(rca.get("timeline_narrative", "")), styles["Body"]))

    # ---- Appendix: correlated clusters & anomalies ----
    story.append(PageBreak())
    story.append(Paragraph("Appendix A: Correlated Event Clusters", styles["SectionHeading"]))
    rows = [["Cluster", "Start", "End", "Sources", "Max Severity", "Events"]]
    for c in clusters:
        rows.append([str(c["cluster_id"]), _esc(c["start_time"]), _esc(c["end_time"]),
                     _esc(", ".join(c["sources"])), _esc(c["max_severity"]), str(c["event_count"])])
    t = Table(rows, colWidths=[1.5 * cm, 3.5 * cm, 3.5 * cm, 3.5 * cm, 2.5 * cm, 1.5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
    ]))
    story.append(t)

    story.append(Paragraph("Appendix B: Detected Anomalies", styles["SectionHeading"]))
    for a in anomalies:
        story.append(Paragraph(f"- <b>[{_esc(a.get('type'))}]</b> {_esc(a.get('explanation',''))}", styles["Body"]))

    doc.build(story)
    return output_path
